// This file is auto-generated by Supabase.
// YOU CAN EDIT THIS FILE MANUALLY.
// We'll generate it for you upon first connection to a project.
// But feel free to edit it to match your schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      groups: {
        Row: {
          id: string
          image_url: string | null
          name: string
        }
        Insert: {
          id?: string
          image_url?: string | null
          name: string
        }
        Update: {
          id?: string
          image_url?: string | null
          name?: string
        }
        Relationships: []
      }
      posts: {
        Row: {
          content: string
          created_at: string
          id: string
          image_url: string | null
          user_id: string
        }
        Insert: {
          content: string
          created_at?: string
          id?: string
          image_url?: string | null
          user_id: string
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          image_url?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "posts_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          full_name: string | null
          id: string
        }
        Insert: {
          avatar_url?: string | null
          full_name?: string | null
          id: string
        }
        Update: {
          avatar_url?: string | null
          full_name?: string | null
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      tasks: {
        Row: {
          created_at: string
          description: string
          due_date: string | null
          id: string
          price: number
          status: Database["public"]["Enums"]["task_status"]
          subject: string
          title: string
          type: Database["public"]["Enums"]["task_type"]
          user_id: string
        }
        Insert: {
          created_at?: string
          description: string
          due_date?: string | null
          id?: string
          price?: number
          status?: Database["public"]["Enums"]["task_status"]
          subject: string
          title: string
          type: Database["public"]["Enums"]["task_type"]
          user_id: string
        }
        Update: {
          created_at?: string
          description?: string
          due_date?: string | null
          id?: string
          price?: number
          status?: Database["public"]["Enums"]["task_status"]
          subject?: string
          title?: string
          type?: Database["public"]["Enums"]["task_type"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      task_status: "open" | "in_progress" | "completed"
      task_type: "request" | "offer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
